--- #YAML:1.0
name:                     CPAN-Testers-Data-Release
version:                  0.01
abstract:                 CPAN Testers Release database generator
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  CPAN::Testers::Common::DBUtils: 0
  Config::IniFiles:               0
  File::Basename:                 0
  File::Path:                     0
  Getopt::Long:                   0
  IO::File:                       0
recommends:
  Test::More:                     0.70
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
  Test::CPAN::Meta:               0.08
build_requires:
  Test::More:                     0.01

provides:
  CPAN::Testers::Data::Release:
    file:     lib/CPAN/Testers/Data/Release.pm
    version:  0.01
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Data-Release

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
